db_path = "/var/lib/corrosion/state.db"

api_addr = "[::]:8080"

admin_path = "/app/admin.sock"

metrics_addr = "0.0.0.0:9090"

bootstrap = ["sandwich-builtin.internal:8787"]

schema_paths = ["/app/schemas"]

[log]
colors = false

# log_format = "json"
