# fly.toml app configuration file generated for corrodemo on 2023-06-09T22:55:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "corrodemo"
primary_region = "yul"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "corrodemo.fly.dev"
  PORT = "8080"
  CORRO_BASEURL="http://top1.nearest.of.ccorrosion.internal:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
