# fly.toml app configuration file generated for corro-sandwiches-ex on 2023-06-29T19:08:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sandwich-builtin"
primary_region = "yyz"
kill_signal = "SIGTERM"

[mounts]
source = "corro_data"
destination = "/var/lib/corrosion"

[deploy]
  strategy = "immediate"

[env]
  CORRO_BUILTIN = "1"
  CORRO_BASEURL = "http://localhost:8080"
  PHX_HOST = "sandwich-builtin.fly.dev"
  PORT = "8081"
  RUST_BACKTRACE = "1"
# RUST_LOG="info,foca=debug"

[[services]]
  internal_port = 8081
  protocol = "tcp"
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[metrics]
  port = 9090
  path = "/"